-- Set context
USE ROLE ACCOUNTADMIN;

-- Create a Snowflake DB
CREATE OR REPLACE DATABASE KAFKA_DB COMMENT = 'Database for Continuous Data Pipeline demo';

-- Create a Snowflake ROLE
USE ROLE SECURITYADMIN;
  CREATE OR REPLACE ROLE KAFKA_CONNECTOR_ROLE;
  GRANT ALL ON DATABASE KAFKA_DB TO ROLE KAFKA_CONNECTOR_ROLE;
  GRANT ALL ON DATABASE KAFKA_DB TO ACCOUNTADMIN;
  GRANT ALL ON SCHEMA KAFKA_DB.PUBLIC TO ROLE KAFKA_CONNECTOR_ROLE;
  GRANT ALL ON FUTURE TABLES IN SCHEMA KAFKA_DB.PUBLIC TO KAFKA_CONNECTOR_ROLE;
  GRANT ALL ON SCHEMA KAFKA_DB.PUBLIC TO ROLE ACCOUNTADMIN;
  GRANT CREATE TABLE ON SCHEMA KAFKA_DB.PUBLIC TO ROLE KAFKA_CONNECTOR_ROLE;
  GRANT CREATE STAGE ON SCHEMA KAFKA_DB.PUBLIC TO ROLE KAFKA_CONNECTOR_ROLE;
  GRANT CREATE PIPE ON SCHEMA KAFKA_DB.PUBLIC TO ROLE KAFKA_CONNECTOR_ROLE;
USE ROLE ACCOUNTADMIN;
  GRANT EXECUTE TASK ON ACCOUNT TO ROLE KAFKA_CONNECTOR_ROLE;

-- Create Snowflake WAREHOUSES (for admin & tasks purpose)
USE ROLE ACCOUNTADMIN;
  CREATE OR REPLACE WAREHOUSE KAFKA_ADMIN_WAREHOUSE
    WAREHOUSE_SIZE = 'XSMALL'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    SCALING_POLICY = 'STANDARD'
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for Kafka admin activities';
  GRANT USAGE ON WAREHOUSE KAFKA_ADMIN_WAREHOUSE TO ROLE KAFKA_CONNECTOR_ROLE;
  GRANT USAGE ON WAREHOUSE KAFKA_ADMIN_WAREHOUSE TO ROLE ACCOUNTADMIN;

  CREATE OR REPLACE WAREHOUSE KAFKA_TASK_WH
    WAREHOUSE_SIZE = 'XSMALL'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    SCALING_POLICY = 'STANDARD'
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for Continuous ingestion - Tasks';
  GRANT USAGE ON WAREHOUSE KAFKA_TASK_WH TO ROLE KAFKA_CONNECTOR_ROLE;
  GRANT USAGE ON WAREHOUSE KAFKA_TASK_WH TO ROLE ACCOUNTADMIN;

-- Create a Snowflake USER
USE ROLE ACCOUNTADMIN;
  CREATE OR REPLACE USER KAFKA_DEMO
   PASSWORD = 'Password123!'
   LOGIN_NAME = KAFKA_DEMO
   DISPLAY_NAME = KAFKA_DEMO
   DEFAULT_WAREHOUSE = KAFKA_ADMIN_WAREHOUSE
   DEFAULT_ROLE = KAFKA_CONNECTOR_ROLE
   DEFAULT_NAMESPACE = KAFKA_DB
   MUST_CHANGE_PASSWORD = FALSE
   RSA_PUBLIC_KEY="<your_public_key>";
  GRANT ROLE KAFKA_CONNECTOR_ROLE TO USER KAFKA_DEMO;
  GRANT ROLE KAFKA_CONNECTOR_ROLE TO USER ADMIN;
