-- Set the context
USE ROLE KAFKA_CONNECTOR_ROLE;
USE DATABASE KAFKA_DB;
USE SCHEMA PUBLIC;
USE WAREHOUSE KAFKA_ADMIN_WAREHOUSE;

-- Clickstream view from AVRO records
CREATE OR REPLACE SECURE VIEW CLICKSTREAM_VW AS
SELECT
    DATEADD(MS,RECORD_METADATA:CreateTime,'1970-01-01') CREATE_TIME,
    RECORD_CONTENT:_time::string _TIME,
    RECORD_CONTENT:agent::string AGENT,
    RECORD_CONTENT:bytes::string BYTES,
    RECORD_CONTENT:ip::string IP,
    RECORD_CONTENT:referrer::string REFERRER,
    RECORD_CONTENT:remote_user::string REMOTE_USER,
    RECORD_CONTENT:request::string REQUEST,
    RECORD_CONTENT:status::string STATUS,
    RECORD_CONTENT:time::string TIME,
    RECORD_CONTENT:userid::string USERID
    FROM CLICKSTREAM;

-- Pageviews view from AVRO records
CREATE OR REPLACE SECURE VIEW PAGEVIEWS_VW AS
SELECT
    DATEADD(MS,RECORD_METADATA:CreateTime,'1970-01-01') CREATE_TIME,
    RECORD_CONTENT:pageid::string PAGEID,
    RECORD_CONTENT:userid::string USERID,
    RECORD_CONTENT:viewtime::string VIEWTIME
    FROM PAGEVIEWS;

-- Orders view from AVRO records
CREATE OR REPLACE SECURE VIEW ORDERS_VW AS
SELECT
    DATEADD(MS,RECORD_METADATA:CreateTime,'1970-01-01') CREATE_TIME,
    RECORD_CONTENT:address:city::string CITY,
    RECORD_CONTENT:address:state::string STATE,
    RECORD_CONTENT:address:zipcode::int ZIPCODE,
    RECORD_CONTENT:itemid::string ITEMID,
    RECORD_CONTENT:orderid::int ORDERID,
    RECORD_CONTENT:ordertime::int ORDERTIME,
    RECORD_CONTENT:orderunits::float ORDERUNITS
    FROM ORDERS;

-- Ratings view from AVRO records
CREATE OR REPLACE SECURE VIEW RATINGS_VW AS
SELECT
    DATEADD(MS,RECORD_METADATA:CreateTime,'1970-01-01') CREATE_TIME,
    RECORD_CONTENT:channel::string CHANNEL,
    RECORD_CONTENT:message::string MESSAGE,
    RECORD_CONTENT:rating_id::int RATINGID,
    RECORD_CONTENT:rating_time::int RATINGTIME,
    RECORD_CONTENT:route_id::int ROUTEID,
    RECORD_CONTENT:stars::int STARS,
    RECORD_CONTENT:user_id::int USERID
    FROM RATINGS;

-- Stock_trades view from AVRO records
CREATE OR REPLACE SECURE VIEW STOCK_TRADES_VW AS
SELECT
    DATEADD(MS,RECORD_METADATA:CreateTime,'1970-01-01') CREATE_TIME,
    RECORD_CONTENT:account::string ACCOUNT,
    RECORD_CONTENT:price::int PRICE,
    RECORD_CONTENT:quantity::int QUANTITY,
    RECORD_CONTENT:side::string SIDE,
    RECORD_CONTENT:symbol::string SYMBOL,
    RECORD_CONTENT:userid::string USERID
    FROM STOCK_TRADES;

-- Users view from AVRO records
CREATE OR REPLACE SECURE VIEW USERS_VW AS
SELECT
    DATEADD(MS,RECORD_METADATA:CreateTime,'1970-01-01') CREATE_TIME,
    RECORD_CONTENT:gender::string GENDER,
    RECORD_CONTENT:regionid::string REGIONID,
    RECORD_CONTENT:registertime::int REGISTERTIME,
    RECORD_CONTENT:userid::string USERID
    FROM USERS;
