USE ROLE KAFKA_CONNECTOR_ROLE;
USE WAREHOUSE KAFKA_ADMIN_WAREHOUSE
-- Resume TASK to make it run
ALTER TASK TASK_EXTRACT_AVRO_FROM_CLICKSTRERAM SUSPEND;
ALTER TASK TASK_EXTRACT_AVRO_FROM_PAGEVIEWS SUSPEND;
ALTER TASK TASK_EXTRACT_AVRO_FROM_ORDERS SUSPEND;
ALTER TASK TASK_EXTRACT_AVRO_FROM_RATINGS SUSPEND;
ALTER TASK TASK_EXTRACT_AVRO_FROM_STOCK_TRADES SUSPEND;
ALTER TASK TASK_EXTRACT_AVRO_FROM_USERS SUSPEND;
-- Drop the TASKS
DROP TASK TASK_EXTRACT_AVRO_FROM_CLICKSTRERAM;
DROP TASK TASK_EXTRACT_AVRO_FROM_PAGEVIEWS;
DROP TASK TASK_EXTRACT_AVRO_FROM_ORDERS;
DROP TASK TASK_EXTRACT_AVRO_FROM_RATINGS;
DROP TASK TASK_EXTRACT_AVRO_FROM_STOCK_TRADES;
DROP TASK TASK_EXTRACT_AVRO_FROM_USERS;
USE ROLE ACCOUNTADMIN;
-- Drop the DB
DROP DATABASE KAFKA_DB;
-- Drop the WAREHOUSES
DROP WAREHOUSE KAFKA_ADMIN_WAREHOUSE;
DROP WAREHOUSE KAFKA_TASK_WH;
-- Drop the USER
DROP USER KAFKA_DEMO;
-- Drop the ROLE
DROP ROLE KAFKA_CONNECTOR_ROLE;
